/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2dpbo;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author binta
 */
public class addCreator extends javax.swing.JFrame {
    private Menu gundam;
    private dbConnection db;
    private Boolean isUpdate = false;
    private int selectedID;
    private File fileImage;
    private String filePath;
    private String fileName;
    
    /**
     * Creates new form addCreator
     */
    public addCreator(Menu gundam) {
        initComponents();
        db = new dbConnection();
        this.gundam=gundam;
    }
    
    public addCreator(Menu gundam, int id, String image, String name, String nation){
        initComponents();
        db = new dbConnection();
        this.gundam=gundam;
        this.selectedID = id;
        this.isUpdate=true;
        this.fileName=image;
        btnAdd.setText("Update");
        nameField.setText(name);
        logoField.setText(image);
        nationField.setText(nation);
        titleLabel.setText("Update Creator");
        
        
    }
    public void insertData()
    {
        String name = nameField.getText();
        String nation = nationField.getText();
//        this.fileName = this.fileImage.getName();
        try
        {
            copyImage(this.fileName);
            String sql = "INSERT INTO creator VALUES (NULL, '"+name+"', '"+fileName+"', '"+nation+"')";
            db.updateQuery(sql);
            resetForm();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
            this.gundam.setPanelCreator();
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Failed to add data!");
        }
    }
      public void updateData() throws IOException
    {        
        String name = nameField.getText();
        String nation = nationField.getText();
        if(this.fileImage!= null)
        {
            copyImage(this.fileName);
        }
        String sql = "UPDATE creator SET nama_creator='"+name+"', logo_creator='" + fileName + "', asal_negara='" + nation + "' WHERE id=" + selectedID ;
        int affectedRow = db.updateQuery(sql);
        
        if (affectedRow > 0) {
            // Show Information
            this.gundam.setPanelCreator();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
        } 
        else {
            JOptionPane.showMessageDialog(null, "Data gagal diubah!");
        }
    }
    public void resetForm() {
        // Set All Value Form to Empty
        nameField.setText("");
        nationField.setText("");
        logoField.setText("");
        
    }
    public void copyImage(String img)
    {
        try
        {
            String newPath = "src/tp2dpbo/img/";
            File directory = new File(newPath);
            if(!directory.exists())
            {
                directory.mkdir();
            }
            
            Path copy = Paths.get(newPath + img);
            Path originalPath = Paths.get(this.filePath);
            Files.copy(originalPath, copy, StandardCopyOption.REPLACE_EXISTING);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Failed to upload file!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        nationField = new javax.swing.JTextField();
        logoField = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        titleLabel.setText("Add Creator");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Nama Creator : ");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Asal Negara  : ");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Logo : ");

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameField)
                                .addComponent(nationField)
                                .addComponent(logoField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1)
                    .addComponent(logoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jButton2))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
        {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            this.fileImage = chooser.getSelectedFile();
            this.fileName = this.fileImage.getName();
            this.filePath = this.fileImage.getAbsolutePath();
            logoField.setText(this.filePath);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Failed to browse file!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         if(isUpdate == false)
            insertData();
        else {
            try {
                updateData();
            } catch (IOException ex) {
                Logger.getLogger(addCreator.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
         this.dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField logoField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nationField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
