/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2dpbo;
import java.sql.ResultSet;
import java.awt.GridLayout;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author binta
 */
public final class Menu extends javax.swing.JFrame {
    private dbConnection db;
    private String panel;
    private boolean isUpdate;
    /**
     * Creates new form Menu
     * @return 
     * @throws java.io.IOException
     */
    public String getPanel(){
        return panel;
    }
    public void setPanel(String panel){
        this.panel=panel;
    }
    public Menu(String name) throws IOException
    {
        initComponents();
        db = new dbConnection();
       
        nameField.setText(name);
        setPanelCreator();
        
    }
   public void setIsUpdate(boolean isUpdate) {
      this.isUpdate = isUpdate;
    }
    public boolean getIsUpdate() {
      return isUpdate;
    }
    
     public void onDataUpdate() throws IOException {
        // Refresh data in Frame1 here
        if(this.panel.equals("film")){
            setPanelCreator();
        }else{
            setPanelGundam();
        }
    }
    public void setPanelCreator() throws IOException 
    {
        String sql = "SELECT * FROM creator ";
        ResultSet res = db.selectQuery(sql);
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
       
        
        try {
            while(res.next())
            {
                int selectedID = res.getInt("id");
                String Name = res.getString("nama_creator");
                String Nation = res.getString("asal_negara");
                String Image = res.getString("logo_creator");
                mainPanel.add(new cardCreator(this, selectedID, Image, Name, Nation));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        mainPanel.revalidate();
        mainPanel.repaint();
        setPanel("creator");
    }
    
    public void setPanelGundam()throws IOException
    {
        String sql = "SELECT * FROM gundam ";
        ResultSet res = db.selectQuery(sql);
      
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
       
        
        try {
            while(res.next())
            {
                int selectedID = res.getInt("id");
                String Name = res.getString("nama_gundam");
                int Creator = res.getInt("creator_gundam");
                String Type = res.getString("jenis_gundam");
                String Size = res.getString("ukuran_gundam");
                String Image = res.getString("gambar_gundam");
                mainPanel.add(new cardGundam(this, selectedID, Name, Image, Creator,Size,Type));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        mainPanel.revalidate();
        mainPanel.repaint();
        setPanel("gundam");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        btnCreator = new javax.swing.JButton();
        btnGundam = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        nameField = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainPanel);

        btnCreator.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCreator.setText("Creator");
        btnCreator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatorActionPerformed(evt);
            }
        });

        btnGundam.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnGundam.setText("Gundam");
        btnGundam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGundamActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        nameField.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        nameField.setText("name");

        btnAdd.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnGundam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(230, 230, 230)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(nameField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreator)
                    .addComponent(btnGundam)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatorActionPerformed
        try {
            // TODO add your handling code here:
            setPanelCreator();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreatorActionPerformed

    private void btnGundamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGundamActionPerformed
        try {
            // TODO add your handling code here:
            setPanelGundam();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGundamActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login l = new login();
        l.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        this.setIsUpdate(false);
        if(this.panel.equals("creator")){
        addCreator a = new addCreator(this);
        a.setVisible(true);
        a.setDefaultCloseOperation(addCreator.DISPOSE_ON_CLOSE);
        }
        else{
            
        addGundam a = new addGundam(this);
        a.setVisible(true);
        a.setDefaultCloseOperation(addGundam.DISPOSE_ON_CLOSE);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCreator;
    private javax.swing.JButton btnGundam;
    private javax.swing.JButton btnLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameField;
    // End of variables declaration//GEN-END:variables
}
